-- cartographer_ros_config.yaml

map_frame: map
tracking_frame: base_link
published_frame: base_link
odometry_frame: odom
provide_odom_frame: true

-- Laser and IMU sensor configuration
laser_min_range: 0.5
laser_max_range: 30.0
laser_angle_resolution: 0.01
laser_scan_topic: /scan  # Modify with your LiDAR topic
imu_topic: /imu/data  # Modify with your IMU topic

-- Pose optimization
pose_graph:
  optimization_problem:
    huber_scale: 1e2
    linear_programming_solver_options:
      use_ipopt: true

