# rtabmap_launch.yaml

# Global settings
rtabmap:
  ros__parameters:
    frame_id: base_link
    map_frame: map
    subscribe_depth: true
    subscribe_rgb: true
    subscribe_scan: true
    subscribe_scan_cloud: false
    subscribe_imu: true

# Map settings
rtabmap_cloud: true
memory_strategy: 2  # Save more data
max_maps: 5  # Max number of maps stored

# Optimization settings
optimize_from_dense: true

